### ISSUE TITLE
Repeated save file dialogue when using `make`

### ISSUE THREAD

**Issue by jfb-h** [tecosaur/DataToolkit.jl#13]
When using `make` to build a derived dataset and choosing to insert the generated script as a file (f) instead of inline (i), the save file dialogue repeats indefinitely and the only option seems to abort the process.

**Comment by tecosaur** [comment]
It is! Fixed in https://github.com/tecosaur/DataToolkitCommon.jl/commit/e9f3b89c04cf0f1520b1937846135777073f0c1b

**Comment by jfb-h** [comment]
Thanks a lot!
