### ISSUE TITLE
Access a file as a path, without a loader

### ISSUE THREAD

**Issue by asinghvi17** [tecosaur/DataToolkit.jl#22]
I was looking at using DataToolkit to manage external data in package tests, and was wondering if it's possible to have it return a file path or something?  I need the file path specifically to point my package to it.

The rest of the data management tools are pretty slick!

**Comment by tecosaur** [comment]
FYI once a6bb5a9bcd7e91d2e97c167305c1d6c28efdcf1e makes it into the next release, you'll be able to `open` a `DataSet` to a `FilePathsBase.AbstractPath` :slightly_smiling_face:
