### ISSUE TITLE
Badge-doc links in Readme 404

### ISSUE THREAD

**Issue by behinger** [tecosaur/DataToolkit.jl#46]
The correct link should be: https://tecosaur.github.io/DataToolkit.jl/main/ I inferred, but currently links point to 
```
#+html: <a href="https://tecosaur.github.io/DataToolkitDocs/ref/stable/"><img src="https://img.shields.io/badge/docs-stable-blue.svg"></a>
#+html: <a href="https://tecosaur.github.io/DataToolkit.jl/dev/"><img src="https://img.shields.io/badge/docs-dev-blue.svg"></a>
```

The package looks reeeeally good though, thanks!

**Comment by tecosaur** [comment]
There's been a bit of a reshuffle, hence the broken links. I'll see about updating them :slightly_smiling_face: 

Ta!

**Comment by brianguenter** [comment]
I second the request to fix the links. Just tried to get to the docs and both release and dev links were broken.

**Comment by tecosaur** [comment]
Unfortunately there is no soothing release link since there's been no release since the monorepo reshuffle. I'll fix the docs badge link though.

**Comment by tecosaur** [comment]
Fixed (at last).
