### ISSUE TITLE
Keep existing REPL statements when going to Data REPL

### ISSUE THREAD

**Issue by Yuan-Ru-Lin** [tecosaur/DataToolkit.jl#47]
Oftentimes I type commands for wrong modes e.g.

```julia
julia> add DataToolkit
```

Luckily, when I enter `Pkg` by pressing `]` between `julia>` and the statement, it remains.

```julia
julia> |add DataToolkit  # press ] at |
(environment) pkg> add DataToolkit
```

However, this is not the case for the Data REPL.

```julia
(environment) pkg> |command_for_DTK  # press delete since I was in a wrong mode
julia> |command_for_DTK  # press } at | to go to Data REPL
(environment) data> |  # statement is gone :(
```

**Comment by tecosaur** [comment]
Good news, I'm aware of the exact issue you describe, and it should be fixed already in the in-development 0.10 release 🙂.
