### ISSUE TITLE
Undocumented data mode `add` feature

### ISSUE THREAD

**Issue by KaiAragaki** [tecosaur/DataToolkit.jl#51]
Hello!

The [tutorial](https://tecosaur.github.io/DataToolkit.jl/main/tutorial/) makes use of `data> add NAME SOURCE` (both for `add iris SOURCE` and `add boston SOURCE`). 

However, the ability to forgo including `from` or `f` appears not to be documented in `data> add help`.

May be tangentially related to #41

**Comment by tecosaur** [comment]
Hi Kai!

Looking at the usage example, it currently reads:

```
data> add NAME
data> add NAME from SOURCE
data> add from SOURCE
```

how about I just extend that to

```
data> add NAME
data> add NAME from SOURCE
data> add NAME SOURCE
data> add from SOURCE
```

**Comment by KaiAragaki** [comment]
Sounds good to me! Do you think removing the next line regarding the shorthand of `from` to `f` should be modified?

Thank you!
